Repository camunda-community-hub/zeebe-cluster-helm, pull requests merged in 2020-04, with the labels that each got.

#33 Dynamic Addition for Exporters to Zeebe Cluster Containers
  zeebe-cluster/templates/configmap.yaml
  zeebe-cluster/templates/statefulset.yaml
Labels: size/XS

#53 creates local exporters dir
  zeebe-cluster/templates/configmap.yaml
Labels: needs-ok-to-test, size/XS

#54 Change gateway-deployment readiness port to use .Values.serviceGatewayName
  zeebe-cluster/templates/gateway-deployment.yaml
Labels: needs-ok-to-test, size/XS

#55 feat: upgrade Zeebe to 0.23.0
  Makefile
  README.md
  zeebe-cluster/templates/configmap.yaml
  zeebe-cluster/templates/gateway-deployment.yaml
  zeebe-cluster/templates/statefulset.yaml
  zeebe-cluster/values.yaml
Labels: size/L

#58 chore: add command API port in broker service
  zeebe-cluster/templates/service.yaml
Labels: size/XS
