Repository camunda-community-hub/zeebe-cluster-helm, pull requests merged in 2020-02, with the labels that each got.

#23 only deploy ServiceMonitor if prometheusOperator is enabled
  README.md
  zeebe-cluster/templates/service-monitor.yaml
  zeebe-cluster/values.yaml
Labels: needs-ok-to-test, size/M

#25 Added support for nodeSelector, tolerations and affinity
  README.md
  zeebe-cluster/templates/statefulset.yaml
  zeebe-cluster/values.yaml
Labels: needs-ok-to-test, size/S

#28 chore(prometheus): adjust prometheus cfg structure
  README.md
  zeebe-cluster/requirements.yaml
  zeebe-cluster/templates/NOTES.txt
  zeebe-cluster/values.yaml
Labels: size/S

#29 Set proper default values to avoid warnings when overriding
  zeebe-cluster/values.yaml
Labels: needs-ok-to-test, size/XS

#31 fix: fixes indentation of extraInitContainers
  zeebe-cluster/templates/statefulset.yaml
Labels: bug, size/XS
