Repository camunda-community-hub/zeebe-cluster-helm, pull requests merged in 2020-03, with the labels that each got.

#36 fix: set securityContext under spec.containers
  zeebe-cluster/templates/statefulset.yaml
Labels: approved, bug, lgtm, size/XS

#39 Make Service and Zeebe Container port names configurable via values.yaml
  zeebe-cluster/templates/service.yaml
  zeebe-cluster/templates/statefulset.yaml
Labels: approved, ok-to-test, size/S

#45 feat: allow setting custom environment to brokers
  README.md
  zeebe-cluster/templates/statefulset.yaml
  zeebe-cluster/values.yaml
Labels: approved, enhancement, lgtm, ok-to-test, size/S

#43 feat: improves startup.sh script
  zeebe-cluster/templates/configmap.yaml
  zeebe-cluster/templates/statefulset.yaml
Labels: enhancement, lgtm, ok-to-test, size/M

#34 ADD Namespace in NOTES.txt
  zeebe-cluster/templates/NOTES.txt
Labels: lgtm, needs-ok-to-test, size/XS

#35 Standalone Gateway by default
  README.md
  zeebe-cluster/templates/configmap.yaml
  zeebe-cluster/templates/gateway-deployment.yaml
  zeebe-cluster/templates/gateway-service.yaml
  zeebe-cluster/templates/service.yaml
  zeebe-cluster/templates/statefulset.yaml
  zeebe-cluster/templates/tests/test-connection.yaml
  zeebe-cluster/values.yaml
Labels: size/L
