Repository camunda-community-hub/zeebe-cluster-helm, pull requests merged in 2020-05, with the labels that each got.

#61 Fix Test Connection pod template
  zeebe-cluster/templates/tests/test-connection.yaml
Labels: needs-ok-to-test, size/XS

#67 feat(gateway): support arbitary env variables
  README.md
  zeebe-cluster/templates/gateway-deployment.yaml
  zeebe-cluster/values.yaml
Labels: approved, size/S

#68 Allow custom annotations on the gateway Deployment pods
  README.md
  zeebe-cluster/templates/gateway-deployment.yaml
Labels: approved, needs-ok-to-test, size/XS

#62 Add PodDisruptionBudgets
  README.md
  zeebe-cluster/templates/gateway-poddisruptionbudget.yaml
  zeebe-cluster/templates/poddisruptionbudget.yaml
  zeebe-cluster/values.yaml
Labels: needs-ok-to-test, size/M

#70 Update configmap.yaml
  zeebe-cluster/templates/configmap.yaml
Labels: needs-ok-to-test, size/XS
