Repository camunda-community-hub/zeebe-cluster-helm, pull requests merged in 2020-09, with the labels that each got.

#92 feat(gateway): Add ability to set gateway resource limits
  zeebe-cluster/templates/gateway-deployment.yaml
  zeebe-cluster/values.yaml
Labels: needs-ok-to-test, size/XS

#90 Update Zeebe version to 0.24.2
  zeebe-cluster/Chart.yaml
  zeebe-cluster/values.yaml
Labels: size/XS

#96 feat(gateway): Enable setting nodeSelector / affinity / tolerations on gateway deployment
  zeebe-cluster/templates/gateway-deployment.yaml
Labels: needs-ok-to-test, size/S

#95 feat: Add ability to set pod-level labels
  zeebe-cluster/templates/gateway-deployment.yaml
  zeebe-cluster/templates/statefulset.yaml
Labels: needs-ok-to-test, size/XS

#94 fix(broker): Fix the loglevel value reference for broker statefulset
  zeebe-cluster/templates/statefulset.yaml
Labels: needs-ok-to-test, size/XS
