Repository camunda-community-hub/zeebe-cluster-helm, pull requests merged in 2020-06, with the labels that each got.

#72 gateway: use pod ip as cluster host
  zeebe-cluster/templates/gateway-deployment.yaml
Labels: size/S

#78 chore: bump default zeebe version
  zeebe-cluster/values.yaml
Labels: size/XS

#81 chore(values): remove gc settings
  zeebe-cluster/values.yaml
Labels: approved, size/XS

#79 chore: standardizes labels
  zeebe-cluster/Chart.yaml
  zeebe-cluster/templates/_helpers.tpl
  zeebe-cluster/templates/configmap.yaml
  zeebe-cluster/templates/gateway-deployment.yaml
  zeebe-cluster/templates/gateway-poddisruptionbudget.yaml
  zeebe-cluster/templates/gateway-service.yaml
  zeebe-cluster/templates/poddisruptionbudget.yaml
  zeebe-cluster/templates/service-monitor.yaml
  zeebe-cluster/templates/service.yaml
  zeebe-cluster/templates/statefulset.yaml
Labels: approved, size/L

#82 Make JVM memory limit dynamic by setting -XX:MaxRAMPercentage
  zeebe-cluster/values.yaml
Labels: size/XS
