Repository camunda-community-hub/zeebe-cluster-helm, pull requests merged in 2021-08, with the labels that each got.

#117 Update elasticsearch/kibana image tags
  charts/zeebe-cluster-helm/values.yaml
Labels: size/S

#120 Zell example
  charts/zeebe-cluster-helm/templates/NOTES.txt
Labels: approved

#122 Adding value to parameterize the type of service to be created for the Cluster Gateway
  README.md
  charts/zeebe-cluster-helm/templates/gateway-service.yaml
  charts/zeebe-cluster-helm/values.yaml
Labels: size/XS, lgtm, approved
